version: "3.7"
services:
    db:
      build: ./db
      container_name: db
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: camel100985camel
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: camel100985camel
      networks:
        website_network:
          aliases:
            - wordpress
    wordpress:
      build: .
      container_name: wordpress
      ports:
        - "80"
      networks:
        website_network:
          aliases:
            - wordpress
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: camel100985camel
        WORDPRESS_DB_NAME: wordpress
    nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - "443:443"
        - "80"
      networks:
        website_network:
          aliases:
            - nginx-proxy
networks:
  website_network:
    name: website_network
volumes:
  db_data:
    driver: local
    name: db_data
